#ifndef TCPPROTOCOL_GLOBAL_H
#define TCPPROTOCOL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TCPPROTOCOL_LIBRARY)
#  define TCPPROTOCOLSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TCPPROTOCOLSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TCPPROTOCOL_GLOBAL_H
